# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Factory Intelligence
tagline:             'Using data science to improve manufacturing'
description:         'A site all about Lean, Six Sigma, statistics, and data science that are used to make products faster, cheaper, and higher quality.'
url:                 http://mattrauch.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Matt Rauch
  url:               https://twitter.com/mattrauch91
  email:             rauch.matt@gmail.com

# Custom vars
version:             1.0.0
